#!/usr/bin/env zsh

ICON_FONT="JetBrainsMono Nerd Font Mono"
LABEL_FONT="JetBrainsMono Nerd Font"

PLUGIN_DIR="$HOME/.config/sketchybar/plugins"

SPOTIFY_EVENT="com.spotify.client.PlaybackStateChanged"

sketchybar --bar \
    height=30 \
    color=0x00000000 \
    margin=0 \
    sticky=on \
    padding_left=10 \
    padding_right=10 \
    display=main

# Alternatiive background colors
# label.color=0xffffffff
# background.color=0x9924273a
sketchybar --default \
    background.color=0x66494d64 \
    background.corner_radius=5 \
    background.padding_right=5 \
    background.height=26 \
    icon.font="$ICON_FONT:Bold:22.0" \
    icon.padding_left=5 \
    icon.padding_right=5 \
    label.font="$LABEL_FONT:Bold:13.0" \
    label.color=0xffcad3f5 \
    label.y_offset=0 \
    label.padding_left=0 \
    label.padding_right=5

sketchybar --add item current_space left \
    --set current_space \
    background.color=0xff8aa9f9 \
    icon.color=0xff24273a \
    icon.font="$ICON_FONT:Bold:15.0" \
    label.drawing=off \
    script="$PLUGIN_DIR/current_space.sh" \
    --subscribe current_space space_change mouse.clicked

sketchybar --add item front_app left \
    --set front_app \
    background.color=0xffa6da95 \
    background.padding_left=0 \
    background.padding_right=0 \
    icon.y_offset=1 \
    icon.color=0xff24273a \
    icon.font="$ICON_FONT:Bold:22.0" \
    label.drawing=no \
    script="$PLUGIN_DIR/front_app.sh" \
    --add item front_app.separator left \
    --set front_app.separator \
    background.color=0x00000000 \
    background.padding_left=-3 \
    icon= \
    icon.color=0xffa6da95 \
    icon.font="$ICON_FONT:Bold:20.0" \
    icon.padding_left=0 \
    icon.padding_right=0 \
    icon.y_offset=1 \
    label.drawing=no \
    --add item front_app.name left \
    --set front_app.name \
    background.color=0x00000000 \
    background.padding_right=0 \
    icon.drawing=off \
    label.font="$LABEL_FONT:Bold:14.0" \
    label.drawing=yes

sketchybar --add event spotify_change $SPOTIFY_EVENT \
    --add item spotify center \
    --set spotify \
    background.padding_left=0 \
    background.padding_right=0 \
    icon= \
    icon.y_offset=1 \
    icon.padding_left=6 \
    icon.font="$ICON_FONT:Bold:22.0" \
    label.drawing=off \
    script="$PLUGIN_DIR/spotify.sh" \
    --subscribe spotify spotify_change mouse.clicked


sketchybar --add bracket front_app_bracket \
    front_app \
    front_app.separator \
    front_app.name \
    --subscribe front_app front_app_switched

sketchybar --add item weather.moon right \
    --set weather.moon \
    background.color=0x667dc4e4 \
    background.padding_right=-1 \
    icon.color=0xff181926 \
    icon.font="$ICON_FONT:Bold:22.0" \
    icon.padding_left=4 \
    icon.padding_right=3 \
    label.drawing=off \
    --subscribe weather.moon mouse.clicked

sketchybar --add item weather right \
    --set weather \
    icon= \
    icon.color=0xfff5bde6 \
    icon.font="$ICON_FONT:Bold:15.0" \
    update_freq=1800 \
    script="$PLUGIN_DIR/weather.sh" \
    --subscribe weather system_woke


sketchybar --add item clock right \
    --set clock \
    icon=󰃰 \
    icon.color=0xffed8796 \
    icon.font="$ICON_FONT:Bold:22.0" \
    update_freq=10 \
    script="$PLUGIN_DIR/clock.sh"

sketchybar --add item battery right \
    --set battery \
    update_freq=20 \
    icon.font="$ICON_FONT:Bold:22.0" \
    script="$PLUGIN_DIR/battery.sh"

sketchybar --add item volume right \
    --set volume \
    icon.color=0xff8aadf4 \
    label.drawing=true \
    script="$PLUGIN_DIR/volume.sh" \
    --subscribe volume volume_change

# osascript -e 'quit app "Rectangle"'
# open -a Rectangle

##### Finalizing Setup #####
sketchybar --update
sketchybar --trigger space_change
